apiVersion: v1
kind: Pod
metadata:
  name: app-readiness-probe
spec:
  containers:
  - name: app
    image: my-app-image
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5