apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: demo-container
    image: us-central1-docker.pkg.dev/devops-test-420111/olukyanenko/simple:v2
    ports:
    - containerPort: 8080
      name: http